import sys
import time
import base64
import requests
import jwt  # Used to decode the returned JWT to show claims
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import serialization, hashes

REGISTRY_URL = "http://localhost:8000/api/agents"

def main():
    print("=== Agent ID Platform - Deployer CLI Simulation ===")
    print("Beginning sequential execution of Steps 0 to 5...")

    # ==========================================
    # PHASE 1: AGENT INITIALIZATION (Steps 0 & 1)
    # ==========================================
    print("\n--- PHASE 1: Agent Registry & Provisioning (Steps 0 & 1) ---")
    boot_payload = {
        "name": "BankTransferAgent",
        "description": "Autonomous agent authorized to manage transfers.",
        "model": "gpt-4o"
    }

    try:
        print(f" Deployer asking to Register blank agent to registry: {REGISTRY_URL}...")
        response = requests.post(REGISTRY_URL, json=boot_payload, timeout=5)
        
        if response.status_code != 200:
            print(f"[ERROR] Failed to register agent: {response.status_code} - {response.text}")
            sys.exit(1)
            
        result = response.json()
        agent_id = result.get("agent_id")
        status = result.get("status")
        runtime_id = result.get("runtime_id")
        
        print("\n[SUCCESS] Agent Registered (Step 0 & 1 complete):")
        print(f"  Agent ID:   {agent_id[:8]}... (a 128-bit UUID value generated by the Provider at Step 0)")
        print(f"  Status:     {status} (Blank idle state)")
        print(f"  Runtime ID: {runtime_id} (a unique worker thread ID spawned by the Provider at Step 1)")

    except requests.exceptions.RequestException as e:
        print(f"\n[ERROR] Connection failed: {str(e)}")
        print("Please verify that the Agent Registry Service is running on port 8000.")
        sys.exit(1)

    time.sleep(1.5)

    # ==================================================
    # PHASE 2: PROMPT & IDENTITY HANDSHAKE (Steps 2 to 5)
    # ==================================================
    print("\n--- PHASE 2: Prompt Submission & Cryptographic Handshake (Steps 2 to 5) ---")
    
    prompt_url = f"{REGISTRY_URL}/{agent_id}/prompt"
    # Fetch Audit Authority Public Key to encrypt sensitive Deployer Accountability ID
    print("\n[SECURITY] Fetching Audit Authority public key from port 8004...")
    try:
        audit_res = requests.get("http://localhost:8004/api/audit/public-key", timeout=5)
        if audit_res.status_code != 200:
            print(f"[ERROR] Failed to fetch Audit public key: {audit_res.text}")
            sys.exit(1)
        audit_pub_pem = audit_res.json().get("public_key_pem")
        print("[SECURITY] Audit Authority public key retrieved successfully.")
    except Exception as e:
        print(f"[ERROR] Connection to Audit Authority failed: {str(e)}")
        print("Please verify that the Audit Authority Service is running on port 8004.")
        sys.exit(1)

    # Encrypt Deployer Accountability ID ('Jane Doe') client-side before sending to Provider
    print("[SECURITY] Encrypting Deployer Accountability ID ('Jane Doe') client-side using JWE (RSA-OAEP)...")
    try:
        audit_pub_key = serialization.load_pem_public_key(audit_pub_pem.encode('utf-8'))
        plain_accountability_id = "Jane Doe"
        encrypted_bytes = audit_pub_key.encrypt(
            plain_accountability_id.encode('utf-8'),
            padding.OAEP(
                mgf=padding.MGF1(algorithm=hashes.SHA256()),
                algorithm=hashes.SHA256(),
                label=None
            )
        )
        encrypted_b64 = base64.b64encode(encrypted_bytes).decode('utf-8')
        print(f"[SECURITY] Generated JWE ciphertext: {encrypted_b64[:30]}...")
    except Exception as e:
        print(f"[ERROR] Encryption failed: {str(e)}")
        sys.exit(1)

    prompt_payload = {
        "deployer_prompt": "Transfer 1000 USD from my checking account to my savings account",
        "receiving_service": "bank.com",
        "deployer_identifier_on_service": "deployer's username on bank.com",
        "deployer_identifier": "deployer #101",
        "deployer_accountability_id": encrypted_b64
    }

    try:
        print(f"Submitting execution prompt to: {prompt_url}...")
        response = requests.post(prompt_url, json=prompt_payload, timeout=10)
        
        if response.status_code != 200:
            print(f"[ERROR] Prompt submission failed: {response.status_code} - {response.text}")
            sys.exit(1)
            
        result = response.json()
        status = result.get("status")
        agent_id_jwt = result.get("agent_id_jwt")
        
        print("\n[SUCCESS] Cryptographic handshake completed!")
        print(f"  Agent State: {status}")
        
        if agent_id_jwt:
            print("\n[SECURE] Cryptographic Agent ID JWT received:")
            print(f"  Raw Token (truncated): {agent_id_jwt[:30]}... (an ES256 Provider-signed composite JWT compiled at Step 5, length: {len(agent_id_jwt)} bytes)")
            
            # Decode the JWT to inspect claims without signature verification
            try:
                decoded_payload = jwt.decode(agent_id_jwt, options={"verify_signature": False})
                print("\n  Decoded Claims (Step 5 - Active Agent ID State):")
                print(f"    Issuer (Provider ID):      {decoded_payload.get('iss')} (verifiable platform identity)")
                print(f"    Subject (Agent Instance):  {decoded_payload.get('sub')[:28]}... (bound subject identifying the active agent instance)")
                print(f"    Deployer Identifier:       {decoded_payload.get('deployer_identifier')} (registered identifier of deployer on provider)")
                print(f"    Deployer Accountability:   {decoded_payload.get('deployer_accountability_id')} (accountability name of the deployer)")
                print(f"    Shutdown Webhook Command:  {decoded_payload.get('agent_instance_shutdown_command')} (emergency shutdown command established at Step 5)")
                print(f"    Agent Public Key (trunc):  {decoded_payload.get('agent_public_key')[:45].strip()}... (a P-256 EC public key dynamically generated by the Agent at Step 1)")
                
                # Check nested Developer Attestation
                dev_att_jwt = decoded_payload.get("developer_attestation")
                if dev_att_jwt:
                    print("\n    --- Nested Developer Attestation ---")
                    decoded_dev_payload = jwt.decode(dev_att_jwt, options={"verify_signature": False})
                    print(f"      Issuer (Developer ID):   {decoded_dev_payload.get('iss')} (verifiable developer identity)")
                    print(f"      Foundation Model ID:    {decoded_dev_payload.get('foundation_model_identifier')} (identifier of model used by agent)")
                    print(f"      Safety Evidence URL:    {decoded_dev_payload.get('foundation_model_safety_evidence')} (developer safety testing evidence published at Step 4)")
                
                # Demonstrate Audit Authority Decryption (available on demand)
                print("\n    --- [DEMO] Querying Audit Authority to Decrypt Accountability ID ---")
                try:
                    decrypt_url = "http://localhost:8004/api/audit/decrypt"
                    headers = {
                        "Authorization": "Bearer audit_secret_token"
                    }
                    decrypt_payload = {
                        "ciphertext_base64": decoded_payload.get('deployer_accountability_id')
                    }
                    print(f"      Sending JWE ciphertext to Audit Service: {decrypt_url}...")
                    decrypt_res = requests.post(decrypt_url, json=decrypt_payload, headers=headers, timeout=5)
                    if decrypt_res.status_code == 200:
                        decrypted_name = decrypt_res.json().get("decrypted_value")
                        print(f"      [SUCCESS] Audit Authority decrypted accountability ID: {decrypted_name}")
                    else:
                        print(f"      [ERROR] Decryption failed: {decrypt_res.status_code} - {decrypt_res.text}")
                except Exception as e:
                    print(f"      [ERROR] Could not connect to Audit Service: {str(e)}")
            except Exception as e:
                print(f"  [ERROR] Failed to decode JWT claims: {str(e)}")
        else:
            print("\n[WARNING] No Agent ID JWT returned from the server.")

    except requests.exceptions.RequestException as e:
        print(f"\n[ERROR] Connection failed: {str(e)}")
        sys.exit(1)

    print("\nExact protocol flow simulation (Steps 0 to 5) completed.")

if __name__ == "__main__":
    main()
